name: Deploy to github pages (beta)
on:
  push:
    branches:
      - "feature/*"
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages (beta)
    runs-on: ubuntu-latest
    steps:

      # Install NodeJS
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'

      # Checkout branch
      - name: Checkout branch
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: npm i

      # Build website
      - name: Build website
        run: npm run build

      # Push to beta website repo
      - name: Push to beta website repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'dist'
          destination-github-username: 'Timbogen'
          destination-repository-name: 'beta-website'
          user-email: niederer.tim@gmail.com
          target-branch: main
